import type { OrderCard } from './types';

// Replace this with a prop or a fetch when the backend is ready.
export const ORDERS: OrderCard[] = [
  {
    id: 'green-leaf-kitchen',
    category: 'food',
    icon: '🍔',
    title: 'Green Leaf Kitchen',
    status: 'Out for delivery',
    statusKind: 'ongoing',
    subtitle: '3 items · Arriving 8:20 PM',
    actions: ['Track'],
    group: 'Ongoing',
  },
  {
    id: 'ride-to-airport',
    category: 'rides',
    icon: '🚗',
    title: 'Ride to Airport',
    status: 'Driver en route',
    statusKind: 'ongoing',
    subtitle: 'Arjun · Swift · 4 min away',
    actions: ['Track'],
    group: 'Ongoing',
  },
  {
    id: 'ac-repair',
    category: 'homeservices',
    icon: '🔧',
    title: 'AC Repair',
    status: 'Scheduled',
    statusKind: 'upcoming',
    subtitle: 'Tomorrow, 11:00 AM · Ramesh K.',
    actions: ['Reschedule'],
    group: 'Upcoming',
  },
  {
    id: 'dental-checkup',
    category: 'healthcare',
    icon: '❤️',
    title: 'Dental Checkup',
    status: 'Confirmed',
    statusKind: 'upcoming',
    subtitle: 'Aug 25, 4:30 PM · Dr. Meera',
    actions: ['Reschedule'],
    group: 'Upcoming',
  },
  {
    id: 'fresh-mart-groceries',
    category: 'groceries',
    icon: '🛒',
    title: 'Fresh Mart Groceries',
    status: 'Delivered',
    statusKind: 'done',
    subtitle: '12 items · ₹840 · Aug 19',
    actions: ['Reorder', 'Invoice'],
    group: 'Completed',
  },
  {
    id: 'ride-to-office',
    category: 'rides',
    icon: '🚗',
    title: 'Ride to Office',
    status: 'Completed',
    statusKind: 'done',
    subtitle: '₹165 · Aug 18',
    actions: ['Rebook'],
    group: 'Completed',
  },
  {
    id: 'spice-route',
    category: 'food',
    icon: '🍔',
    title: 'Spice Route',
    status: 'Delivered',
    statusKind: 'done',
    subtitle: '2 items · ₹420 · Aug 17',
    actions: ['Reorder'],
    group: 'Completed',
  },
  {
    id: 'deep-home-cleaning',
    category: 'homeservices',
    icon: '🔧',
    title: 'Deep Home Cleaning',
    status: 'Completed',
    statusKind: 'done',
    subtitle: '₹1,200 · Aug 14',
    actions: ['Book again'],
    group: 'Completed',
  },
];
