import { Platform, StyleSheet } from 'react-native';
import { COLORS } from './colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'ios' ? 54 : 20,
    paddingBottom: 14,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.card,
  },
  headerTitle: { color: COLORS.white, fontSize: 17, fontWeight: '700' },

  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 16, paddingBottom: 24 },

  subHeader: { color: COLORS.gray, fontSize: 13, lineHeight: 18, marginTop: 4, marginBottom: 20 },

  sectionLabel: {
    color: COLORS.grayDim,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginTop: 4,
  },

  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
  },

  divider: { height: 1, backgroundColor: COLORS.border },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  rowIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowTextWrap: { flex: 1, paddingRight: 12 },
  rowTitleLine: { flexDirection: 'row', alignItems: 'center' },
  rowTitle: { color: COLORS.white, fontSize: 15, fontWeight: '600' },
  rowSubtitle: { color: COLORS.gray, fontSize: 12.5, lineHeight: 17, marginTop: 3 },

  badge: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
    backgroundColor: COLORS.cardAlt,
    borderWidth: 1,
    borderColor: COLORS.accentDeep,
  },
  badgeText: { color: COLORS.accent, fontSize: 10.5, fontWeight: '700' },

  balanceCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginBottom: 24,
  },
  balanceCardTitle: { color: COLORS.white, fontSize: 15, fontWeight: '700', marginBottom: 16 },
  balanceRow: { flexDirection: 'row', alignItems: 'center' },
  balanceStat: { flex: 1, alignItems: 'center' },
  balanceDivider: { width: 1, height: 30, backgroundColor: COLORS.border },
  balanceValue: { color: COLORS.white, fontSize: 16, fontWeight: '700' },
  balanceValueAccent: { color: COLORS.accent },
  balanceLabel: { color: COLORS.gray, fontSize: 11, marginTop: 4, textAlign: 'center' },
  balanceHistoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: 6,
  },
  balanceHistoryText: { color: COLORS.accent, fontSize: 13, fontWeight: '700' },

  toast: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 34,
    backgroundColor: '#1D1E22',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: COLORS.accentDeep,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  toastText: { color: COLORS.white, fontSize: 13.5, fontWeight: '600', textAlign: 'center' },

  // ---- Bottom sheet modal (shared by Wallet / Add Money / UPI / Card modals) ----
  modalOverlay: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.border,
    marginBottom: 14,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  sheetTitle: { color: COLORS.white, fontSize: 17, fontWeight: '700' },
  sheetCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.cardAlt,
  },

  primaryBtn: {
    backgroundColor: COLORS.accent,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 18,
  },
  primaryBtnDisabled: { opacity: 0.4 },
  primaryBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },

  secondaryBtn: {
    backgroundColor: COLORS.cardAlt,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  secondaryBtnText: { color: COLORS.white, fontSize: 14, fontWeight: '600' },

  dangerBtnText: { color: COLORS.danger, fontSize: 14, fontWeight: '600' },

  input: {
    backgroundColor: COLORS.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.white,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 12,
  },
  inputLabel: { color: COLORS.gray, fontSize: 12, marginTop: 14, marginBottom: 2 },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.cardAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  chipActive: { borderColor: COLORS.accent, backgroundColor: 'rgba(95,163,0,0.18)' },
  chipText: { color: COLORS.white, fontSize: 13.5, fontWeight: '600' },
  chipTextActive: { color: COLORS.accentLight },

  amountBig: { color: COLORS.white, fontSize: 34, fontWeight: '800', textAlign: 'center', marginTop: 4 },
  amountCurrency: { color: COLORS.gray, fontSize: 14, textAlign: 'center', marginTop: 2 },

  txnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  txnTitle: { color: COLORS.white, fontSize: 14, fontWeight: '600' },
  txnDate: { color: COLORS.grayDim, fontSize: 11.5, marginTop: 2 },
  txnAmount: { fontSize: 14, fontWeight: '700' },
  txnAmountPositive: { color: '#7EC400' },
  txnAmountNegative: { color: COLORS.white },

  detailKeyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  detailKey: { color: COLORS.gray, fontSize: 13 },
  detailValue: { color: COLORS.white, fontSize: 13, fontWeight: '600' },
});
